### ISSUE TITLE
Objects are not exported from 'namespace:ACTman'

### ISSUE THREAD

**Issue by Chris-M-P** [compsy/ACTman#10]
There seems to be an issue with objects not being exported from 'namespace:ACTman'

The following code (using the csv files from [http://ykkunkels.com/actman/](http://ykkunkels.com/actman/)):
```
library(ACTman)
ACTman::ACTman(workdir = "C:/mydata", myACTdevice = "MW8", lengthcheck = FALSE)
```

Gives this error: `Error: 'ACTman' is not an exported object from 'namespace:ACTman'`

**Comment by emerencia** [comment]
Thanks. We accidentally removed the export. It should be fixed now.

**Comment by Chris-M-P** [comment]
Yep, seems fine now
