### ISSUE TITLE
Problem reading in a file that has a measurement at midnight.

### ISSUE THREAD

**Issue by markspan** [compsy/ACTman#14]
When reading in a datafile (e.g., the datasets from the website of yoram) an issue arises when that dataset has a measurement at midnight. The default behavior of the formatter (strptime) is to not format midnight (:o).

I was able to load the example data when I changed ACTdata.r line 394 to explicitly format the time with the date.

   ACTdata.1.sub$Date = format(ACTdata.1.sub$Date, "%Y-%m-%d %H:%M:%S")  
   write.table(ACTdata.1.sub, quote = FALSE, row.names = FALSE,   
     col.names = FALSE, file = paste(gsub(pattern = ".csv",   
       replacement = "", x = ACTdata.files\[i\]), "MANAGED.txt"))  
 

I am unsure if this is the "solution of choice", but it seems to work with at least the demo-data.

**Comment by emerencia** [comment]
Thanks for the fix, I'll merge it
